name: resume
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.9
  http: ^1.4.0
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  syncfusion_flutter_charts: ^29.2.5
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
